apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - volumes/persistentvolumeclaim.yaml
  - manifests/statefulset.yaml
  - manifests/configmaps.yaml
  - manifests/secret.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/ingress.yaml
  - manifests/cronjob.yaml